loader:
  path: resources/fresh_start.csv
  interval_min: 1
  start_immediately: True
publisher:
  connection:
    host: some-rabbit
    port: 5672
    virtual_host: /
  route:
    exchange: ""
    routing_key: q
log:
  version: 1
  handlers:
    console:
      class : logging.StreamHandler
      level   : DEBUG
      stream  : ext://sys.stdout
    file:
      level   : DEBUG
      class : logging.FileHandler
      mode: w
      filename: loader.log
#      maxBytes: 1024
#      backupCount: 3
  loggers:
    loader:
      level   : DEBUG
      handlers: [console, file]

