loader:
  path: resources/fresh_start.csv
publisher:
  connection:
    host: 172.18.0.2
    port: 5672
    virtual_host: /
  route:
    exchange: ""
    routing_key: q
log:
  version: 1
  handlers:
    console:
      class : logging.StreamHandler
      level   : INFO
      stream  : ext://sys.stdout
    file:
      class : logging.FileHandler
      mode: w
      filename: loader.log
#      maxBytes: 1024
#      backupCount: 3
  loggers:
    loader:
      handlers: [console, file]

